[env]
APP_REPLAY_DURATION = "60"
RABBITMQ_HOST = "localhost"
RABBITMQ_VHOST = "/"
RABBITMQ_PORT = "5672"
RABBITMQ_QUEUE_ENV = "dev"
RABBITMQ_USERNAME = "guest"
RABBITMQ_PASSWORD = "guest"
RUST_LOG = "debug"
AXUM_LISTEN_HOST = "0.0.0.0"
AXUM_LISTEN_PORT = "3000"
