on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  check:
    name: 'Check'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
      - name: Run cargo check
        run: cargo check --release

  test:
    name: 'Build and test'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        run: cargo test --verbose --release -- --nocapture
